default['kafka']['kafka_version'] = '0.8.1.2.2.4.2-2'
default['kafka']['network.threads'] = '2'
default['kafka']['io.threads'] = '8'
default['kafka']['log.dirs'] = '/data/d1/kafka,/data/d2/kafka'
default['kafka']['broker.id']['tzkf4002'] = '1'
default['kafka']['broker.id']['tzkf4003'] = '2'
default['kafka']['broker.id']['tzkf4004'] = '3'
default['jmxtrans_version'] = '250-1'
