default['kafka']['kafka_version'] = '0.8.1.2.2.0.0-2041'
default['kafka']['network.threads'] = '2'
default['kafka']['io.threads'] = '8'
default['kafka']['log.dirs'] = '/data/d1/kafka,/data/d2/kafka'
default['kafka']['broker.id']['precise64'] = '9'
default['kafka']['broker.id']['tzns4006.grid.uj1.inmobi.com'] = '1'
default['kafka']['broker.id']['tzns4007.grid.uj1.inmobi.com'] = '2'
default['kafka']['broker.id']['tzns4010.grid.uj1.inmobi.com'] = '3'
