default['kafkaMirroring']['instanceid']['uh1']={ "krfl4001" => 1}
default['kafkaMirroring']['collectorid']['uh1']='uh1collector'
default['kafkaMirroring']['hdfsid']['uh1']='gold'
default['kafkaMirroring']['version']= '0.6.13'
default['kafkaMirroringConfig']['version']= '0.6.13'
default['kafkaMirroring']['staging_dir']= '/data/kafka/staging'
default['kafkaMirroring']['log_dir']= '/var/log/kafkamirroring'
default['kafkaMirroring']['offset_dir']= '/data/inmobi/kafkamirroring/offsets'
default['kafkaMirroring']['spool_dir']= '/data/inmobi/kafkamirroring/spooling'
default['kafkaMirroringConfig']['prodconf']= '/opt/inmobi/config/KafkaMirroringConfig/prod/'
default['kafkaMirroringConfig']['confighome']= '/opt/inmobi/config/KafkaMirroringConfig/'
default['kafkaSupervisorConfig']['confighome']= '/etc/supervisor/conf.d'
